version: 2.1

jobs:
  build:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker build -t bytevictor/animeflv-api .
      - run: docker run -t -v `pwd`:/test bytevictor/animeflv-api
      